export class Dictionary{
  public static Lenguage = {
    en: {
      home: 'Home',
      about: 'About',
      aboutMe: 'About Me',
      contact: 'Contact',
      selectLanguage: 'Select Language',
      portuguese: 'Portuguese',
      labelLanguage: 'English',
      english: 'English',
      title: 'Hello! My name is ',
      subtitle: 'front-end developer',
      cv: 'Curriculum Vitae',
      project: 'Projects',
      moreBtn: 'See more',
    },
    pt:{
      home: 'Início',
      about: 'Sobre',
      aboutMe: 'Sobre Mim',
      services: 'Serviços',
      contact: 'Contato',
      blog: 'Blog',
      selectLanguage: 'Selecione o idioma',
      labelLanguage: 'Português',
      portuguese: 'Português',
      english: 'Inglês',
      title: 'Oi! Meu nome é ',
      subtitle: 'Desenvolvimento front-end',
      cv: 'Curriculum Vitae',
      project: 'Projetos',
      moreBtn: 'Ver mais',
    },
  }
}
