export class Dictionary{
  public static Lenguage = {
    en: {
      home: 'Home',
      about: 'About',
      aboutMe: 'About Me',
      contact: 'Contact',
      selectLanguage: 'Select Language',
      portuguese: 'Portuguese',
      labelLanguage: 'English',
      english: 'English',
      title: 'Hello! My name is ',
      subtitle: 'Developer',
      cv: 'Curriculum Vitae',
      project: 'Projects',
      moreBtn: 'See more',
      score: 'Score',
      textTerminal: 'Type "snake" to access the snake game',
      gameText: 'You won, to return to the home page press the ESC button',
    },
    pt:{
      home: 'Início',
      about: 'Sobre',
      aboutMe: 'Sobre Mim',
      services: 'Serviços',
      contact: 'Contato',
      blog: 'Blog',
      selectLanguage: 'Selecione o idioma',
      labelLanguage: 'Português',
      portuguese: 'Português',
      english: 'Inglês',
      title: 'Oi! Meu nome é ',
      subtitle: 'Desenvolvedor',
      cv: 'Curriculum Vitae',
      project: 'Projetos',
      moreBtn: 'Ver mais',
      score: 'Pontos',
      textTerminal: 'Digite "snake" para jogar o jogo da cobrinha',
      gameText: 'Você venceu, para voltar para pagina inicial aperte o botão ESC',
    },
  }
}
